version: "3"
services:
   springboot-docker:
    container_name: spring-boot-demo
    restart: always
    image: springboot-docker
    build: .
    ports:
      - 8087:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
   mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      - "C:/Users/Badal Kumar Jha/Desktop/db:/var/lib/mysql"
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root



     
     


    
 
    
